### PR TITLE
Fix const correctness errors introduced in d3c66a6b2.

### PR DESCRIPTION
**Pull request by ericonr**
The dirname and basename functions from libgen.h may (or not) change the
string passed to them, which is why their parameter is "char *", not
"const char *". Using "const_cast<char *>" so the compiler didn't
complain was the wrong change to make, since the underlying data of
those strings would be changed anyway.

This commit fixes that by adding a basename() wrapper in osutils.cc,
based on the existing dirname() wrapper, and using it where applicable.

### CODE REVIEW

**Comment by lyonel** [comment]
doesn't link:
```
g++ -L./core/ -g -Wl,--as-needed -o lshw lshw.o -llshw -lresolv
/usr/bin/ld: ./core//liblshw.a(hw.o): in function `hwNode::setLogicalName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/me/Source/lshw/src/core/hw.cc:1086: undefined reference to `basename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ./core//liblshw.a(pci.o): in function `scan_pci(hwNode&)':
/home/me/Source/lshw/src/core/pci.cc:1174: undefined reference to `basename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/me/Source/lshw/src/core/pci.cc:1176: undefined reference to `basename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ./core//liblshw.a(sysfs.o): in function `sysfs_getbustype(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/me/Source/lshw/src/core/sysfs.cc:106: undefined reference to `basename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ./core//liblshw.a(sysfs.o): in function `sysfstobusinfo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/me/Source/lshw/src/core/sysfs.cc:154: undefined reference to `basename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: ./core//liblshw.a(sysfs.o):/home/me/Source/lshw/src/core/sysfs.cc:165: more undefined references to `basename(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:69: lshw] Error 1
```
please test before submitting

**Comment by ericonr** [comment]
```
g++ -L./core/ -g -Wl,--as-needed -o lshw lshw.o -llshw -lresolv
make[1]: Leaving directory '/lshw/src'
```

I will check on glibc, then...

**Comment by ericonr** [comment]
Ah! It's an issue on glibc only. In `<libgen.h>` they have:

```
/* Copyright (C) 1996-2019 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <http://www.gnu.org/licenses/>.  */

#ifndef _LIBGEN_H
#define _LIBGEN_H	1

#include <features.h>

__BEGIN_DECLS

/* Return directory part of PATH or "." if none is available.  */
extern char *dirname (char *__path) __THROW;

/* Return final component of PATH.

   This is the weird XPG version of this function.  It sometimes will
   modify its argument.  Therefore we normally use the GNU version (in
   <string.h>) and only if this header is included make the XPG
   version available under the real name.  */
extern char *__xpg_basename (char *__path) __THROW;
#define basename	__xpg_basename

__END_DECLS

#endif /* libgen.h */
```

So the function defined in `osutils.c` ends up being named `__xpg_basename`... Can I name it `my_basename`? Otherwise I can't think of any clean fix.

**Comment by ericonr** [comment]
@lyonel given 0140f7f28a09d33dc46531212d095da5e021b027, I believe I can close this issue?

**Comment by ericonr** [comment]
Closing this, since I believe all I had done has been commited in some way or another.

Hope I helped by bringing it to your attention.

**Comment by lyonel** [comment]
thx (and sorry for the delayed replies, I don't regularly come to Github - all development happens on ezix.org)
